[package]
name = "pinkc"
version = "0.1.0"
authors = ["Nicholas Mazzuca <npmazzuca@gmail.com>"]

[[bin]]
name = "pinkc"
path = "src/driver.rs"

[dependencies]
argparse = "0.2.1"
typed-arena = "1.1.0"
